parameters:
    app.default_uri: '%env(APP_DEFAULT_URI)%'
    app.canonical_host: '%env(APP_CANONICAL_HOST)%'
    app.admin.base_path: '%env(APP_ADMIN_BASE_PATH)%'
    app.uploads_dir: '%env(APP_UPLOADS_DIR)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Doctrine/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Uid\Command\GenerateUlidCommand: ~
    Symfony\Component\Uid\Command\GenerateUuidCommand: ~
    Symfony\Component\Uid\Command\InspectUlidCommand: ~
    Symfony\Component\Uid\Command\InspectUuidCommand: ~
