monolog:
    channels:
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/main.log"
                max_files: 10
                level: debug
                channels:
                    - "!deprecation"
                    - "!event"
            deprecation:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/deprecation.log"
                max_files: 10
                level: debug
                channels:
                    - deprecation
            event:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/event.log"
                max_files: 10
                level: debug
                channels:
                    - event
            console:
                type: console
                process_psr_3_messages: false
                channels:
                    - "!console"
                    - "!doctrine"
                    - "!event"

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes:
                    - 404
                    - 405
                channels:
                    - "!event"
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes:
                    - 404
                    - 405
                buffer_size: 50
            nested:
                type: group
                members:
                    - main_stderr
                    - main_file
            main_stderr:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            main_file:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/main.log"
                max_files: 10
                level: debug
            console:
                type: console
                process_psr_3_messages: false
                channels:
                    - "!doctrine"
                    - "!event"
            deprecation:
                type: stream
                channels:
                    - deprecation
                path: php://stderr
